name: zn
description: Zn
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  go_router: ^5.0.1
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  podcast_search: ^0.5.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.0.14
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
